import 'package:infosec/models/book.dart';
import 'package:infosec/models/book_category.dart';
import 'package:infosec/models/site.dart';
import 'package:infosec/models/video_course.dart';

import 'models/news.dart';
import 'models/video_category.dart';

List<VideoCategory> videoCategories = [
  VideoCategory(
    id: 1,
    name: "Web pentesting",
    description: "Web saytlarni pentesting qilish uchun mavjud tool lardan foydalanish bo'yicha videolar",
    image: 'https://i.ibb.co/YNg47sJ/Web-Application-Penetration-Testing-WAPT.png',
  ),
  VideoCategory(
    id: 2,
    name: "Tarmoq xavfsizligi",
    description: "Tarmoq yaratish va uning xavfsizligini ta'minlash bo'yicha videolar",
    image: 'https://www.logsign.com/uploads/ensuring_network_security_e34d6ce4bb.png',
  ),
  VideoCategory(
    id: 3,
    name: "Operatsion tizimlar",
    description: "Windows va Linux operatsion tizimlaridan foydalanish bo'yicha videolar",
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1d8ZgEeIvZWvww-L5ayWcWR1pPae9frXuhw&usqp=CAU',
  ),
  VideoCategory(
    id: 4,
    name: "CTF topshiriqlarini yechish",
    description: "CTF topshiriqlarini yechish bo'yicha videolar",
    image: 'https://i.ibb.co/NYqvVwL/Join-The-First-Cellebrite-Capture-the-Flag-CTF-Event-CTF-blog-header-1536x768.png',
  ),
];

List<VideoCourse> videoCourses = [
  VideoCourse(
    id: 1,
    name: "Web saytni tool lar orqali test qilish",
    description: "Web saytning avtomatik testlash dasturlari orqali zaifliklarini aniqlash",
    url: "https://www.youtube.com/live/ZBi8Qa9m5c0?feature=shared",
    image: 'https://www.alpinesecurity.com/wp-content/uploads/2020/02/web+application+penetration+testing.jpg',
    videoCategoryId: 1,
  ),
  VideoCourse(
    id: 2,
    name: "Metasploit dasturidan foydalanish bo'yicha ko'nikmalarga ega bo'lish",
    description: "Metasploit dasturining imkoniyatlari va undan foydalanish",
    url: "https://youtu.be/8lR27r8Y_ik?feature=shared",
    image: 'https://miro.medium.com/v2/resize:fit:1400/1*waFDh88WH0YeIK3xMP6TjA.png',
    videoCategoryId: 1,
  ),
  VideoCourse(
    id: 3,
    name: "Burpsuite dasturidan foydalanish bo'yicha ko'nikmalarga ega bo'lish",
    description: "Burpsuite dasturi imkoniyatlaridan to'liq foydalanish",
    url: "https://youtu.be/IWWYNDiwYOA?feature=shared",
    image: 'https://uploads-ssl.webflow.com/62efedb360a7998b0e43cb84/6321a0f076706854ff591093_All%20about%20BurpSuite.jpg',
    videoCategoryId: 1,
  ),
  VideoCourse(
    id: 4,
    name: "Nmap dasturidan foydalanish bo'yicha ko'nikmalarga ega bo'lish",
    description: "Nmap dasturi orqali tizim haqida ma'lumotlarga ega bo'lish va uni zaifliklarga tekshirish",
    url: "https://youtu.be/4t4kBkMsDbQ?feature=shared",
    image: 'https://miro.medium.com/v2/resize:fit:540/0*H04gYPUb-lLf0cWC.jpg',
    videoCategoryId: 1,
  ),
  VideoCourse(
    id: 5,
    name: "Tarmoq yaratish",
    description: "CCNA kursi dasturi bo'yicha tarmoq yaratish",
    url: "https://youtu.be/S7MNX_UD7vY?feature=shared",
    image: 'https://media.licdn.com/dms/image/C4E12AQFRZp_eAmDlpA/article-cover_image-shrink_600_2000/0/1627028105433?e=2147483647&v=beta&t=Rt3bd3M3qMcJ-m-9cf5Fxyc6zBljZeB3cU7kvJO5iZc',
    videoCategoryId: 2,
  ),
  VideoCourse(
    id: 6,
    name: "Tarmoq xavfsizligini ta'minlash",
    description: "Firewalllar orqali tarmoq xavfsizligini ta'minlash",
    url: "https://youtu.be/gqE7WMEEY_4?feature=shared",
    image: 'https://www.mofco.ca/wp-content/uploads/2023/02/solutions-fortinet.jpg',
    videoCategoryId: 2,
  ),
  VideoCourse(
    id: 7,
    name: "Linux operatsion sistemasi imkoniyatlaridan to'liq foydalnish",
    description: "Linux operatsion sistemasidagi commandalar va ularning mohiyati",
    url: "https://youtu.be/sWbUDq4S6Y8?feature=shared",
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMvRC83F9TmCa-OOhrGQCeJyez6i7mDu4www&usqp=CAU',
    videoCategoryId: 3,
  ),
  VideoCourse(
    id: 8,
    name: "Windows 2019 serverni sozlash",
    description: "Windows 2019 serverini bosqichma-bosqich sozlash",
    url: "https://youtu.be/Dlll-P4bqag?feature=shared",
    image: 'https://licendi.com/media/magefan_blog/2023/03/Windows-Server-2.png',
    videoCategoryId: 3,
  ),
  VideoCourse(
    id: 9,
    name: "PicoCTF topshiriqlarini yechish",
    description: "PicoCTF topshiriqlarini yechish orqali bilimlarni mustahkamlash",
    url: "https://youtu.be/-iRG9_zFRC4?feature=shared",
    image: 'https://static1.squarespace.com/static/61dd6950eb6a2c53c22fd38b/61dd69a2ec988d336488aa19/644d1daa2bff9f546ddc8534/1685661998931/pico_cover.png?format=1500w',
    videoCategoryId: 4,
  ),
  VideoCourse(
    id: 10,
    name: "GoogleCTF topshiriqlarini yechish",
    description: "GoogleCTF topshiriqlarini yechish bo'yicha video qo'llanma",
    url: "https://youtu.be/voO6wu_58Ew?feature=shared",
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKwthIuUfiV1AfVoxRMMWjUB_RkFv39Jx-D8-ideU5RJssRTbUZGZ8tQgW0E008XS5RBA&usqp=CAU',
    videoCategoryId: 4,
  ),
];

List<BookCategory> bookCategories = [
  BookCategory(
    id: 1,
    name: "Kriptografiya",
    description: "Axborotlarni shifrlash orqali xavfsizligiini ta'minlash bo'yicha algoritmlarga oid qo'llanmalar",
    image: 'https://media.assettype.com/analyticsinsight%2Fimport%2Fwp-content%2Fuploads%2F2021%2F09%2FBest-Cryptography-Books-Beginners-Must-Read.jpg',
  ),
  BookCategory(
    id: 2,
    name: "Tarmoq xavfsizligi",
    description: "Tarmoq yaratish va uning xavfsizligini ta'minlash bo'yicha qo'llanmalar",
    image: 'https://www.oreilly.com/library/cover/0596527632/1200w630h/',
  ),
  BookCategory(
    id: 3,
    name: "Operatsion sistemalardan foydalanish",
    description: "Linux va Windows operatsion sistemalaridan foydalanish bo'yicha qo'llanmalar",
    image: 'https://itsfoss.com/content/images/wordpress/2020/06/best-linux-books-featured-1.jpg',
  ),
  BookCategory(
    id: 4,
    name: "Web pentesting",
    description: "Web sitelarni testlash uchun toollardan foydalanish bo'yicha qo'llanmalar",
    image: 'https://miro.medium.com/v2/resize:fit:1040/1*EbfhU-P8jZNCGpCJc7z0jg.jpeg',
  ),
];

List<Book> books = [
  Book(
    id: 1,
    name: "Pentesting",
    description: "Bu kitobda pentestingni amalga oshirish ketma-ketligi bilan ko'rsatib o'tilgan",
    url: "https://github.com/abdullayevrajab/books/blob/main/penetration%20testing%20ketma%20ketlik.pdf",
    bookCategoryId: 4,
    image: 'https://i.ibb.co/tK31DgF/photo-2024-05-30-00-14-01.jpg',
  ),
  Book(
    id: 2,
    name: "Protocols with meaning",
    description: "Kitobda protocollar ma'nolari va qo'llanilish joylari bilan tushuntirilgan",
    url: "https://github.com/abdullayevrajab/books/blob/main/protocol%20meaning.pdf",
    bookCategoryId: 2,
    image: 'https://i.ibb.co/ZNJ0NXj/photo-2024-05-30-00-13-55.jpg',
  ),
  Book(
    id: 3,
    name: "SSH pentesting",
    description: "Kitobda veb serverning ssh portini mavjud zaifliklar bo'yicha testlash ketma-ketligi tushuntirilgan",
    url: "https://github.com/abdullayevrajab/books/blob/main/ssh%20pentesting.pdf",
    bookCategoryId: 4,
    image: 'https://i.ibb.co/Cw182Nf/photo-2024-05-30-00-13-46.jpg',
  ),
  Book(
    id: 4,
    name: "JohnRipper",
    description: "Kitobda JohnRipper dasturidan foydalanish bo'yicha commandalar tushuntirilgan",
    url: "https://github.com/abdullayevrajab/books/blob/main/use%20johnRipper.pdf",
    bookCategoryId: 1,
    image: 'https://i.ibb.co/k0Lywp5/photo-2024-05-30-00-13-42.jpg',
  ),
  Book(
    id: 5,
    name: "Nmap",
    description: "Kitob Nmap dasturi orqali tizimni arxitekturasini yaratish bo'yicha commandalarni o'z ichiga olgan",
    url: "https://github.com/abdullayevrajab/books/blob/main/nmap%20as%20a%20brute%20force.pdf",
    bookCategoryId: 2,
    image: 'https://i.ibb.co/fvFDKvh/photo-2024-05-30-00-13-39.jpg',
  ),
  Book(
    id: 6,
    name: "Wireshark",
    description: "Tarmoqdagi packetlarni tahlil qilish bo'yicha qo'llanma",
    url: "https://github.com/abdullayevrajab/books/blob/main/use%20wireshark.pdf",
    bookCategoryId: 2,
    image: 'https://i.ibb.co/KGmJGCG/photo-2024-05-30-00-13-36.jpg',
  ),
  Book(
    id: 7,
    name: "Linux commands",
    description: "Linux operatsion sistemasidan foydalanish bo'yicha commandalar",
    url: "https://github.com/abdullayevrajab/books/blob/main/linux%20commands.pdf",
    bookCategoryId: 3,
    image: 'https://i.ibb.co/jTyLfFT/photo-2024-05-30-00-13-32.jpg',
  ),
  Book(
    id: 8,
    name: "Pentesting book",
    description: "Kitobda pentestingni amalga oshirish bo'yicha tool lar va ulardan foydalanish bo'yicha ma'lumotlar mavjud.",
    url: "https://github.com/abdullayevrajab/books/blob/main/web%20pentesting%20book.pdf",
    bookCategoryId: 4,
    image: 'https://i.ibb.co/9vc5mjC/photo-2024-05-30-00-13-27.jpg',
  ),
  Book(
    id: 9,
    name: "Windowsda log larni boshqarish",
    description: "Kitobda Windows tizimida loglarni boshqarish va tahlil qilish usullari tushuntirilgan.",
    url: "https://github.com/abdullayevrajab/books/blob/main/event%20log%20windows%20analays.pdf",
    bookCategoryId: 3,
    image: 'https://i.ibb.co/Gv8XcB5/windows.jpg',
  ),
];

List<Site> sites = [
  Site(
    id: 1,
    name: "Coursera",
    description: "Coursera platformasi Kiberxavfsizlikni o'rganish uchun eng ommabop platformalardan biri hisoblanadi. Platformada google tomonidan ishlab chiqilgan kiberxavfsizlik kursi mavjud.",
    url: "https://www.coursera.org/",
    type: 'Pullik',
    image: 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera.s3.amazonaws.com/media/coursera-rebrand-logo-square.png?auto=format%2Ccompress&dpr=1',
  ),
  Site(
    id: 2,
    name: "Udemy",
    description: "Udemy platformasi butun dunyo ilm ahli uchun muhim platforma hisoblanadi. Platformada kurslar pullik bo'lishiga qaramasdan tez-tez chegirmalar e'lon qilinadi.",
    url: "https://www.udemy.com/",
    type: 'Pullik',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Udemy_logo.svg/800px-Udemy_logo.svg.png',
  ),
  Site(
    id: 3,
    name: "TryHackMe",
    description: "Tryhackme platformasi kiberxavfsizlikni o'rganuvchilar orasida mashhur hisoblanadi va ko'plab soha mutaxassislari tomonidan tavfsiya qilinadi. Shuningdek, amaliyotlarni amalga oshirish uchun virtual kompyuterdan foydalanish imkoniyati mavjud.",
    url: "https://tryhackme.com/",
    type: 'Bepul',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGs9s4fGhmHRgASfqm5Vh3UHYvjA078xzK3Q&usqp=CAU',
  ),
  Site(
    id: 4,
    name: "HackTheBox",
    description: "Hackthebox platformasi kiberxavfsizlik sohasini endi o'rganuvchilar uchun foydali sayt hisoblanadi. Darslar pullik va darsni o'rganib topshiriqlar bajarilgan coin lar taqdim etiladi va bundan boshqa bir modulni sotib olishda foydalanish mumkin.",
    url: "https://www.hackthebox.com/",
    type: 'Pullik',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2BcePfkWtUh4eTRmXZYvUKmFAeN3om536Kw&usqp=CAU',
  ),
  Site(
    id: 5,
    name: "PortSwigger",
    description: "Portswigger platformasida darslarda asosiy e'tibor burpsuite dasturining imkoniyatlarini amaliyot orqali o'rganishga qaratiladi.",
    url: "https://portswigger.net/",
    type: 'Bepul',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTix78vjJLn_Sw_RpwI31qYqA5oiL8s165ZfmkQ4ziBuod_NGj5V6njsAqLtpGnny55a64&usqp=CAU',
  ),
];

List<News> news = [
  News(
    id: 1,
    name: "Crime",
    description: "Ikki aka-uka 25 million dollarni o’g’irlaganlikda ayblanib hibsga olindi",
    url: "https://infosec-blog.uz/1465/",
    image: 'https://infosec-blog.uz/hadsoach/2024/05/image-1-1536x1024.png',
  ),
  News(
    id: 2,
    name: "Apple",
    description: "Apple yollanma hujumlar qurbonlarini ogohlantirish uchun o’z tizimini yangiladi",
    url: "https://infosec-blog.uz/1462/",
    image: 'https://infosec-blog.uz/hadsoach/2024/04/image.png',
  ),
  News(
    id: 3,
    name: "LockBit",
    description: "Qo’lga olingani aytilgan LockBit hakerlar guruhi darknetga qaytdi",
    url: "https://infosec-blog.uz/1452/",
    image: 'https://infosec-blog.uz/hadsoach/2024/03/image.png',
  ),
  News(
    id: 4,
    name: "AnyDesk",
    description: "AnyDesk ga hujum: Kompaniya foydalanuvchilardan parollani alishtirishni so’ramoqda",
    url: "https://infosec-blog.uz/1447/",
    image: 'https://infosec-blog.uz/hadsoach/2024/02/image-2.png',
  ),
  News(
    id: 5,
    name: "Hacking",
    description: "Turkiyaning MeshSec hakerlik guruhi Isroil kinoteatlarida kiberhujum uyushtirdi",
    url: "https://infosec-blog.uz/1428/",
    image: 'https://infosec-blog.uz/hadsoach/2024/01/image.png',
  ),
  News(
    id: 6,
    name: "Hacking",
    description: "Rossiyalik TrickBot zararli dasturini ishlab chiqaruvchisi 5 yilu 4 oyga qamoq jazosiga hukm qilindi",
    url: "https://infosec-blog.uz/1423/",
    image: 'https://infosec-blog.uz/hadsoach/2024/01/image-2-1536x768.png',
  ),
  News(
    id: 7,
    name: "Hacking",
    description: "Lazarus kriptovalyutalarni buzish ortidan 3 milliard o’margan – statistika",
    url: "https://infosec-blog.uz/1411/",
    image: 'https://infosec-blog.uz/hadsoach/2023/12/nk-hackers-1536x1152.webp',
  ),
  News(
    id: 8,
    name: "Hacking",
    description: "Xitoylik hakerlar O’zbekiston va Janubiy Koreyaga kiber hujumlarni amalga oshirmoqda",
    url: "https://infosec-blog.uz/1407/",
    image: 'https://infosec-blog.uz/hadsoach/2023/12/china_hacking_uzbekistan-1536x1024.webp',
  ),
  News(
    id: 9,
    name: "CISCO",
    description: "40000 dan ortiq Cisco IOS XE qurilmalari 0-kun zaifligi yordamida zararlandi",
    url: "https://infosec-blog.uz/1346/",
    image: 'https://infosec-blog.uz/hadsoach/2023/10/cisco-devices-infected-1536x864.webp',
  ),
  News(
    id: 10,
    name: "CYBERAttack",
    description: "Isroilda kiber urush: xakkerlar energiya va mudofaa tizimlarini nishonga olmoqda",
    url: "https://infosec-blog.uz/1322/",
    image: 'https://infosec-blog.uz/hadsoach/2023/10/storm-1433-israel-attack.png',
  ),
  News(
    id: 11,
    name: "Fishing",
    description: "Fishing orqali \$6M o’g’irlagan xakker ushlandi",
    url: "https://infosec-blog.uz/1309/",
    image: 'https://infosec-blog.uz/hadsoach/2023/10/hacker2-jpg.webp',
  ),
  News(
    id: 12,
    name: "Huawei",
    description: "Xitoy: AQSh Huawei serverlariga buzib kirib, salkam 10 yil davomida kiber-josuslik bilan shug’ullangan",
    url: "https://infosec-blog.uz/1210/",
    image: 'https://infosec-blog.uz/hadsoach/2023/09/china-us-cyber-espionage-1536x1024.webp',
  ),
  News(
    id: 13,
    name: "Chrome",
    description: "Brauzeringizni hoziroq yangilang: Chrome dan topilgan yangi zaiflik xakkerlar tomonidan ishlatilmoqda!",
    url: "https://infosec-blog.uz/1261/",
    image: 'https://infosec-blog.uz/hadsoach/2023/09/googlechrome.webp',
  ),
  News(
    id: 14,
    name: "DDoS Attack",
    description: "Shveytsariya hukumati muttasil davom etayotgan DDoS hujumlari va natijada ma’lumotlar tarqab ketayotganligi haqida ogohlantirdi",
    url: "https://infosec-blog.uz/594/",
    image: 'https://infosec-blog.uz/hadsoach/2023/06/swiss-1-jpg.webp',
  ),
  News(
    id: 15,
    name: "Atomic Wallet",
    description: "Xakerlar Atomic Walletdan 35 million dollardan ortiq kriptoni o’g’irlashdi",
    url: "https://infosec-blog.uz/446/",
    image: 'https://infosec-blog.uz/hadsoach/2023/06/crypto_hack_scam_shutterstock_29sep21.webp',
  ),
  News(
    id: 16,
    name: "Ransomware",
    description: "Eronlik xakkerlar “ransomware” niqobi ostida zararli topshiriqlarni amalga oshirayotgani ma’lum bo’ldi",
    url: "https://infosec-blog.uz/53/",
    image: 'https://infosec-blog.uz/hadsoach/2023/04/muddywater-2.jpg',
  ),
];
